name = "DecisionTreeAndRandomForest"
uuid = "2e1a1f2f-ab8e-43f0-b75f-c7407e5d21e0"
authors = ["Marleen Lukei <marleen.lukei@campus.tu-berlin.de>, Cedric Len√üen <c.lenssen@campus.tu-berlin.de>"]
version = "1.0.0-DEV"

[deps]
DocStringExtensions = "ffbed154-4ef7-542d-bbb7-c09d3a79fcae"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"

[compat]
StatsBase = "0.33.21"
julia = "1.10"
